sudo: false
language: ruby
rvm:
- 2.3.3
before_install: gem install bundler -v 1.12.5
deploy:
  provider: rubygems
  api_key:
    secure: FQ3MMkgUAucMVhEgVDptcalMBh9WUVfTZkn6CPttY7GEWDXWKARjFy3TopVz7Eh8y7uy8fuP8gSDdaOmWcnDqGQ8eW9c4TfPaoC5Ttd4f7+1G/y/VvVeeaE/dSucsHTWpobwUAOGLHhArrcRggXHAyNcftbnyfLwha0PgaWXDPTdweNh/f4nbdD72c7TotjjZwUS44ffv+CWNMMVX8zQs5tZ+XTSsWH1RJzjjLK3Mb9adKYA8IkVL2Jitn4TIj95h4r9pqPRHWPdBY6frZ5yF1vZ/7Rny1R7MZ8gST+t2vYO458nVkJYJvkZ4vIJ9bROVXL84iBu2XEuRoB66HSkGYgOcdRBx6joznvf7U4/1qq4mnkaYQijQ3xdy6AmNaymDST2jMKwPIFHm+mKFc5xF8j+ehjE5C3TOX5MQD90mnz4piADey9ha1oy2839gEzOp1mXs/PQcOcPyLtrcoKNfkGENqBguGSOY239c1BAMNhP2IgqW5BzomXieQcw4njLIk3GYXt2ENigQUghTHyzuzNbTu+DgXIbymBYhY/CMs2zIAHE0+Qg2f878VpyAiESK4Ydd5vxFFir+8V9vEXtzqhhsG8el5HC+n5An2eOKvZ5eOSNswNvaqhnsOPkCf9BD6RYEYKfpdS8l7lU95s0BVnnOHMUrzOjLAmNaWy5oS8=
  gem: off_the_grid
  on:
    tags: true
    repo: knuedge/off_the_grid
